/**
 * Build the one file this site does not write by hand.
 *
 * The Ambassador is a static page: HTML, CSS and a script, served as they are.
 * It stays that way. The single exception is the validator, which is not ours
 * to write — it is the published @agent-manifest/client, bundled here into a
 * plain script the page can load with a <script> tag.
 *
 * Why a bundle and not a CDN link: a CDN would make the page depend on a third
 * party being up and serving the bytes we expect. The artefact is committed, so
 * the site has no build step to be served, and CI rebuilds it from the pinned
 * dependency and fails if the committed file differs.
 *
 * The schema travels with it. Every enum, bound and pattern the interview
 * enforces is read from that schema at run time, so this page carries no
 * transcription of the specification that could quietly fall out of date.
 */
import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const clientVersion = require('@agent-manifest/client/package.json').version;
const schemaVersion = require('@agent-manifest/schema/package.json').version;

const ENTRY = `
import { validate } from '@agent-manifest/client/validate';
import { schemaV1_0, SOURCE } from '@agent-manifest/schema';

// The whole surface this page is allowed to use. Anything else it needs, it
// reads out of the schema.
globalThis.AgentManifest = { validate, schema: schemaV1_0, source: SOURCE };
`;

const OUT = 'vendor/agent-manifest-v1.0.js';

await writeFile('.build-entry.js', ENTRY);

await build({
  entryPoints: ['.build-entry.js'],
  bundle: true,
  format: 'iife',
  minify: true,
  target: 'es2019',
  outfile: OUT,
  banner: {
    js:
      `/* Generated by build.mjs — do not edit.\n` +
      ` * @agent-manifest/client ${clientVersion}, @agent-manifest/schema ${schemaVersion}.\n` +
      ` * Rebuild with: npm ci && npm run build\n` +
      ` */`,
  },
  legalComments: 'none',
});

const bytes = (await readFile(OUT)).length;
process.stdout.write(
  `${OUT}: ${bytes} bytes (client ${clientVersion}, schema ${schemaVersion})\n`,
);
